Handle 404 error state in application details view
openshift/hac-dev pull request #160
Opened 2022-07-29 10:50 UTC by rohitkrai03

## Fixes 

- https://issues.redhat.com/browse/HAC-1403

## Description

- Added an error state to handle all application load errors.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

https://user-images.githubusercontent.com/6041994/181743886-d377ba7a-f72f-4fad-ab90-97f63b967e9a.mov

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-07-29 14:58 UTC, rottencandy reviewed
What if we used status box? It has custom text for different errors 404, 403, etc. and is used in other places too.
https://github.com/openshift/hac-dev/blob/dcaca376d1bf02ad03a0306ebed303d9bcd4d4e6/src/shared/components/status-box/StatusBox.tsx#L150

2022-08-01 09:29 UTC, sahil143 requested changes

2022-08-01 09:29 UTC, sahil143 commented on src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
> +          <EmptyStateIcon color="#C9190B" icon={ExclamationCircleIcon} />
use color token
```
import { global_palette_red_100 as redColor } from '@patternfly/react-tokens/dist/js/global_palette_red_100';
```

2022-08-01 09:52 UTC, rohitkrai03 commented
> What if we used status box? It has custom text for different errors 404, 403, etc. and is used in other places too.
> 
> https://github.com/openshift/hac-dev/blob/dcaca376d1bf02ad03a0306ebed303d9bcd4d4e6/src/shared/components/status-box/StatusBox.tsx#L150

@rottencandy I looked at using StatusBox for this but its not updated to look consistent with our current UI in app studio. For some reason the styles were off. Maybe we need to work on a newer StatusBox component for App Studio.

2022-08-01 13:09 UTC, rohitkrai03 commented on src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
> +          <EmptyStateIcon color="#C9190B" icon={ExclamationCircleIcon} />
Done.

2022-08-02 14:59 UTC, jrichter1 commented
/retest

2022-08-03 07:08 UTC, jrichter1 commented
/retest

2022-08-04 10:05 UTC, rottencandy approved these changes
/lgtm

2022-08-04 12:19 UTC, rohitkrai03 commented
All E2E cypress tests are passing locally on this branch rebased with latest master.
<img width="1536" alt="Screenshot 2022-08-04 at 5 48 46 PM" src="https://user-images.githubusercontent.com/6041994/182845106-db61f3fa-84ad-4538-9ca5-b765e5072812.png">

2022-08-04 12:20 UTC, merged