Use feature flags for signup flow
openshift/hac-dev pull request #171
Opened 2022-08-08 16:20 UTC by rottencandy

## Fixes 
https://issues.redhat.com/browse/HAC-1979

## Description
Use feature flags for detecting user signup status.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
(No UI changes)

## How to test or reproduce?

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2022-08-16 14:05 UTC, rohitkrai03 requested changes

2022-08-16 14:05 UTC, rohitkrai03 commented on src/components/NamespacedPage/NamespacedPage.tsx
> +  if (!signupFlag || signupPendingFlag) {
Did you try using the feature flags in the route declaration?

2022-08-17 12:59 UTC, rohitkrai03 requested changes
https://user-images.githubusercontent.com/6041994/185139523-4c70f61a-562d-42d1-aa22-ce43f7d1234d.mov

Singup page is not loading for me if I try with a non singed up user. Also the navigation items should be updated accordingly. It should only render `Singup` nav item if user is not signed up.

2022-08-23 10:00 UTC, rohitkrai03 approved these changes
/approve
/lgtm

2022-08-23 10:32 UTC, rottencandy commented
E2e passing locally
![screenshot-1661250724](https://user-images.githubusercontent.com/20013884/186136700-30b4f0d7-b200-4a7e-84d2-7d67318cfcbb.png)

2022-08-23 14:22 UTC, merged