Add component runtime selector
openshift/hac-dev pull request #233
Opened 2022-10-04 12:27 UTC by rottencandy

## Fixes 
https://issues.redhat.com/browse/HAC-1605

## Description
Add a runtime selector to components review section. That uses the devfile sample API to fetch list of runtimes.
- Allows selecting a runtime when CDQ detection fails to detect one automatically.
- Allows optionally selecting a different runtime if the automatic detection is not satisfactory.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
![0](https://user-images.githubusercontent.com/20013884/193818623-5dea4164-081e-43d8-be77-e605b3bae858.png)
![1](https://user-images.githubusercontent.com/20013884/193818630-130a9462-f24a-4d4d-a14c-14d1032603a6.png)
![2](https://user-images.githubusercontent.com/20013884/193818634-7312b078-763e-4007-9014-5aeeac0e17d2.png)
![3](https://user-images.githubusercontent.com/20013884/193818641-c67e9db1-46b9-464c-b907-6550a51b5962.png)

### Scenario 1: Automatic detection failed

https://user-images.githubusercontent.com/20013884/193818663-80711778-5f4f-4976-b501-246ace162fde.mp4

### Scenario 2: Detection succeeded

https://user-images.githubusercontent.com/20013884/193818709-db4e0e5d-550a-491d-af70-c37f474bea32.mp4

## How to test or reproduce?
Use a non-detectable repo, or try to change the runtime after detection has happened.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2022-10-04 12:28 UTC, rottencandy commented
cc @openshift/team-hacdev-ux

2022-10-05 17:32 UTC, itsptk commented
@rottencandy In the second video 'Scenario 2: Detection succeeded' I guess I was expecting the dropdown to be pre-populated with the detected runtime. Is that not what's happening here? Does that ever happen?

2022-10-05 19:14 UTC, beaumorley commented
@rottencandy In the first video 'Scenario 1: Automatic detection failed' would it be possible to put the error text "Runtime not detected" in the red error message area and not within the form field. And put the "Select a runtime" that is now in red within the field? So swap them?

2022-10-06 11:36 UTC, rottencandy commented
> @rottencandy In the second video 'Scenario 2: Detection succeeded' I guess I was expecting the dropdown to be pre-populated with the detected runtime. Is that not what's happening here? Does that ever happen?

Fixed. The pre population might not always happen since we're currently fetching runtimes from the devfile samples API, and it doesn't provide all the available runtimes. But I think it should work fine when we switch to the devfile stacks API in the future.

2022-10-06 11:36 UTC, rottencandy commented
> @rottencandy In the first video 'Scenario 1: Automatic detection failed' would it be possible to put the error text "Runtime not detected" in the red error message area and not within the form field. And put the "Select a runtime" that is now in red within the field? So swap them?

Updated.
![s](https://user-images.githubusercontent.com/20013884/194302469-df9b2992-0a58-4870-a93f-a5d5ca332e7a.png)

2022-10-06 11:37 UTC, rottencandy commented
/cc @rohitkrai03

2022-10-07 07:18 UTC, rottencandy commented on src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
> +  const [detectedComponents, detectionLoaded, detectionError] = useComponentDetection(
Fixed

2022-10-07 07:18 UTC, rottencandy commented on src/components/ImportForm/ReviewSection/ReviewSection.tsx
> +            showRuntimeSelector
I used this prop to hide the runtime selector in the component settings page, should we be showing it there as well?

2022-10-07 09:25 UTC, rohitkrai03 commented on src/components/ImportForm/ReviewSection/ReviewSection.tsx
> +            showRuntimeSelector
Okay, got it. No we shouldn't show runtime selector in settings page.

2022-10-07 09:54 UTC, rohitkrai03 commented
/retest

2022-10-07 10:31 UTC, rohitkrai03 commented
@rottencandy The PR checks are failing. Seems like an e2e test failure. Can you take a look?

2022-10-07 10:42 UTC, rohitkrai03 approved these changes
/approve

2022-10-07 10:48 UTC, rohitkrai03 requested changes
Okay, I found a few issues while testing multi component detection.

- All the tiles are expanded by default.
- Some of the runtime selectors say `Select runtime` even though it was successfully detected.

https://user-images.githubusercontent.com/6041994/194536258-11e4804c-8461-4df5-a2fd-b1e34bcf846f.mov

2022-10-07 13:05 UTC, rottencandy commented
Fixed. Dropdown will now show `Other` when projectType does not match any of the samples.

https://user-images.githubusercontent.com/20013884/194560703-0e969b6c-ab81-4ea3-8fc5-a3e391b61cb8.mp4

2022-10-07 14:24 UTC, rohitkrai03 requested changes
Updating any one of the runtime selectors in a multi component detection it changes the selection for all and shows error message.

https://user-images.githubusercontent.com/6041994/194576440-80589a51-da31-466c-b452-e867cf45bdec.mov

2022-10-07 14:28 UTC, rottencandy commented
/retest

2022-10-07 15:38 UTC, rottencandy commented
> Updating any one of the runtime selectors in a multi component detection it changes the selection for all and shows error message.

Fixed.

2022-10-10 07:38 UTC, rohitkrai03 approved these changes
/approve

2022-10-10 07:45 UTC, merged