[WIP] update commit list view and add activity view
openshift/hac-dev pull request #306
Opened 2023-01-03 13:49 UTC by sahil143

## Fixes 

https://issues.redhat.com/browse/HAC-2545

## Description

update commit list view

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/9278015/210370042-6507420d-9f6a-41e7-9d25-9d205faae8d9.png">

## How to test or reproduce?

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-01-06 10:51 UTC, rohitkrai03 commented
@sahil143 Unit tests are failing.

2023-01-11 07:49 UTC, karthikjeeyar reviewed
Commits are now sorted based on recent activity! 


Added some of questions/improvements below:

![image](https://user-images.githubusercontent.com/9964343/211754066-6bfca93f-13fc-4d28-b5e4-e80bf7e5c8af.png)

1. Activity tab should be before components tab.
2. @MariaLeonova  Do we need to truncate the Commit message or wrap into two lines ? 
3. `commited at` column should be renamed to `Latest commit at`


Name filter is currently working component name but it should rather work with PR title/commit message.


![Name_Filter](https://user-images.githubusercontent.com/9964343/211749474-a384d617-7f9f-4da7-9be1-8c209bf8b580.gif)

2023-01-11 07:49 UTC, karthikjeeyar commented on src/components/Commits/CommitsListView.tsx
>          </Button>
<img width="418" alt="image" src="https://user-images.githubusercontent.com/9964343/211744880-ff578f06-f1cb-4957-a48d-a0475bc9e74f.png">

Clicking on the `Read more` link does nothing but I think should open a getting started with commit modal like we have in commit details page, @MariaLeonova Please confirm?


<img width="1279" alt="image" src="https://user-images.githubusercontent.com/9964343/211744800-ac522eb6-88cb-40de-820a-c49a00dc591f.png">

2023-01-12 12:20 UTC, MariaLeonova commented
I agree, the commit / PR message should wrap if it's too long. 
We definitely need to embrace the filter by component functionality, but it need to be separate from filter by name. See the suggested design here: [doc](https://docs.google.com/document/d/1RcuEkVC4z_fvfVIrXZ1Oj3N_THPBoSpOFO9pjDFyElU/edit?disco=AAAAnz4u-nU)

2023-01-12 15:30 UTC, MariaLeonova commented
Regarding the Read more: I believe it should open a side panel with the relevant info, similar to https://quickstarts.netlify.app/in-app-documentation.
Ran has raised the question with the docs team, asking for guidance here.

2023-01-13 09:21 UTC, MariaLeonova commented
Per @abigaeljamie 's guidance, the Read more here should be removed for now, since there's no content planned for the side panel. 
[Slack thread](https://redhat-internal.slack.com/archives/C03494X9Y2U/p1673552018822729?thread_ts=1673530199.376579&cid=C03494X9Y2U).

2023-01-13 15:06 UTC, rohitkrai03 commented
Hey, I've merged the PR that fixed the e2e tests - https://github.com/openshift/hac-dev/pull/305. So going forward it would be good to run the e2e tests locally and paste the screenshot here on the PR before merging. Can you do that?

2023-01-16 10:08 UTC, sahil143 commented
@rohitkrai03 I ran the e2e tests. For Private repo, tests are failing.

<img width="602" alt="Screenshot 2023-01-16 at 2 09 15 PM" src="https://user-images.githubusercontent.com/9278015/212649150-67263a57-03dc-4f76-b713-37fc085a502f.png">
<img width="532" alt="Screenshot 2023-01-16 at 2 12 42 PM" src="https://user-images.githubusercontent.com/9278015/212649166-ce75e238-b1d0-47d0-a6c8-a7873383a251.png">
<img width="599" alt="Screenshot 2023-01-16 at 2 15 34 PM" src="https://user-images.githubusercontent.com/9278015/212649176-73a2b989-c4e0-4ce3-830c-968a8aad75d5.png">

2023-01-16 10:09 UTC, sahil143 commented
@karthikjeeyar @MariaLeonova  made updates as requested

<img width="1327" alt="Screenshot 2023-01-16 at 10 20 52 AM" src="https://user-images.githubusercontent.com/9278015/212652788-6edabcee-e8b6-42ab-820c-b70beead24f0.png">

2023-01-17 17:39 UTC, rohitkrai03 requested changes

2023-01-18 04:19 UTC, sahil143 commented on integration-tests/plugins/index.ts
> +    USERNAME: 'sbudhwar-1',
LOL! no removed

2023-01-18 07:18 UTC, closed without merging

2023-01-18 07:24 UTC, sahil143 commented
new PR opened https://github.com/openshift/hac-dev/pull/331