Workspace Details view with list of applications in it
openshift/hac-dev pull request #37
Opened 2022-02-04 16:38 UTC by debsmita1

## Fixes 
https://issues.redhat.com/browse/HAC-542

## Description
- Created a simple tabbed page containing the `Details` & `Applications` tabs
- the Applications tab lists all the applications if available otherwise the empty state is being shown, the most recently deployed application is listed first
- clicking on the application name will take the user to the Composition view page
- added tests

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Gifs for design review 
![Peek 2022-02-04 21-54](https://user-images.githubusercontent.com/22490998/152567201-96ce4589-2903-4f9a-9197-b90a31d8a06d.gif)

## How to test or reproduce?
Goto URL : https://prod.foo.redhat.com:1337/beta/hac/app-studio/workspaces?workspace=Purple_workspace

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2022-02-04 17:59 UTC, debsmita1 commented
/cc @invincibleJai

2022-02-04 17:59 UTC, debsmita1 commented
/cc @rottencandy

2022-02-07 08:11 UTC, debsmita1 commented
/retest

2022-02-07 10:03 UTC, debsmita1 commented
/test test

2022-02-07 14:13 UTC, rottencandy commented on src/shared/components/timestamp/Timestamp.tsx
> +    <div className={classNames('co-timestamp co-icon-and-text', className)}>
These classes aren't defined either.

2022-02-08 07:35 UTC, debsmita1 commented
/assign @rohitkrai03

2022-02-08 11:11 UTC, divyanshiGupta requested changes

2022-02-08 11:11 UTC, divyanshiGupta commented on src/shared/components/simple-tab-nav/SimpleTabNav.tsx
> +  const handleOnClickTab = (event, tabName: string) => {
nit: add event type

2022-02-08 11:11 UTC, divyanshiGupta commented on src/shared/components/table/Table.tsx
> +export default Table;
Please create separate files for all components.

2022-02-08 13:11 UTC, rohitkrai03 requested changes
Don't think we need the tabbed view here for milestone 3. We just need the application list page. The workspace view is going to be built by infra team later on. @invincibleJai maybe we  should have updated the AC to remove that part after our conversation yesterday.

2022-02-08 16:29 UTC, debsmita1 commented
updated the branch name. so closing this and opened a new PR https://github.com/openshift/hac-dev/pull/39

2022-02-08 16:29 UTC, closed without merging