Add name filter to componentList View
openshift/hac-dev pull request #41
Opened 2022-02-10 14:43 UTC by abhinandan13jan

## Fixes 
https://issues.redhat.com/browse/HAC-543

## Description
Adds a name filter to componentListView

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
![filtercomponentlist](https://user-images.githubusercontent.com/24852534/153430854-a3d4985f-49cd-4819-a680-71afcf09b0ff.gif)
<img width="974" alt="Screenshot 2022-02-10 at 6 55 17 PM" src="https://user-images.githubusercontent.com/24852534/153430911-9aff15ab-efe8-44df-8724-98b67bb1a244.png">

## How to test or reproduce?

npm run verify

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2022-02-10 17:58 UTC, rohitkrai03 requested changes
Add some unit tests as well.

2022-02-14 13:14 UTC, abhinandan13jan commented
Added tests

2022-02-14 18:44 UTC, debsmita1 commented
the i18n key can be seen
![Screenshot from 2022-02-15 00-13-43](https://user-images.githubusercontent.com/22490998/153926520-b5eaf04d-c983-407f-8d1f-5062d2061c41.png)

2022-02-15 09:06 UTC, abhinandan13jan commented
> the i18n key can be seen ![Screenshot from 2022-02-15 00-13-43](https://user-images.githubusercontent.com/22490998/153926520-b5eaf04d-c983-407f-8d1f-5062d2061c41.png)

Removed translation as i18n is not yet in place 
<img width="1122" alt="Screenshot 2022-02-15 at 2 35 23 PM" src="https://user-images.githubusercontent.com/24852534/154028905-9d79283f-0071-454a-9c32-64a368c49cc7.png">

2022-02-15 10:42 UTC, rohitkrai03 approved these changes
/lgtm
/approve

2022-02-15 10:44 UTC, merged