include annotation for component creation to new quay repo
openshift/hac-dev pull request #533
Opened 2023-03-30 14:40 UTC by christianvogt

## Fixes 

https://issues.redhat.com/browse/HAC-3623

## Description

Add annotation `image.redhat.com/generate: 'true'` to the Component creation.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

No UI change.

## How to test or reproduce?

Create a new component in the UI. Inspect the yaml.

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-03-30 14:45 UTC, rohitkrai03 requested changes

2023-03-30 14:51 UTC, sbose78 commented on src/utils/create-utils.ts
> +        'image.redhat.com/generate': 'true',
If you did set it upon update, the token would undergo rotation. Good feature, bad for Quay.io getting spammed with API calls 😆

2023-03-31 12:50 UTC, karthikjeeyar commented
/retest

2023-04-04 11:58 UTC, rohitkrai03 commented
/retest

2023-04-04 12:46 UTC, merged