fix typo in enterprise contract security tab
openshift/hac-dev pull request #561
Opened 2023-04-11 10:11 UTC by sahil143

## Fixes 

https://issues.redhat.com/browse/HAC-3696

## Description

typo fixes

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/9278015/231129281-03216eed-a297-483e-ac37-edf68b0ea119.png">

## How to test or reproduce?

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-04-11 15:24 UTC, karthikjeeyar commented
/approve
/lgtm

2023-04-11 15:37 UTC, simonbaird requested changes

2023-04-11 15:38 UTC, simonbaird commented on src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
> +          Enterprise Contract policy is defined using the repo policy language and is described in{' '}
"Rego" is not a typo, that's what the OPA policy language is called.

2023-04-11 15:41 UTC, simonbaird commented on src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
> +          Enterprise Contract policy is defined using the repo policy language and is described in{' '}
I'm not 100% sure about the capitalization, but perhaps "Rego" is better than "rego".

2023-04-12 10:48 UTC, sahil143 commented
/lgtm cancel

2023-04-12 11:10 UTC, sahil143 commented on src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
> +          Enterprise Contract policy is defined using the repo policy language and is described in{' '}
`Rego` is capitalized in the documentation so kept it that way.

2023-04-12 13:46 UTC, simonbaird approved these changes

2023-04-17 09:13 UTC, sahil143 commented
/retest

2023-04-17 13:07 UTC, sahil143 commented
/retest

2023-04-17 17:48 UTC, merged