[WIP] feat(components): add nudges dependencies
openshift/hac-dev pull request #863
Opened 2023-11-16 13:51 UTC by abhinandan13jan

## Fixes 

https://issues.redhat.com/browse/HAC-5433

## Description

<img width="1483" alt="Screenshot 2023-11-16 at 6 35 44 PM" src="https://github.com/openshift/hac-dev/assets/24852534/beba85c7-5e0a-4b21-aff2-b3ba042ca3b3">
<img width="1492" alt="Screenshot 2023-11-16 at 6 36 03 PM" src="https://github.com/openshift/hac-dev/assets/24852534/47b70ab2-a9e2-45cd-a905-08688a72a12d">

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

## How to test or reproduce?

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-11-20 07:43 UTC, MariaLeonova commented
Hi @abhinandan13jan ! Do you think it would be possible to use [these guides](https://www.patternfly.org/components/tree-view/#guides), adding arrows to them? 
Alternatively, I could create an svg for you. Let me know!

2023-11-21 09:24 UTC, abhinandan13jan commented
> Hi @abhinandan13jan ! Do you think it would be possible to use [these guides](https://www.patternfly.org/components/tree-view/#guides), adding arrows to them? Alternatively, I could create an svg for you. Let me know!

@MariaLeonova The tree view is an expandable/collapse collection. Is that what we are looking for. Secondly, there is no way for the incoming arrow, only outgoing one is possible.

Yes, I am using native SVG, if you could give me the exact SVG you think fits best. That would be awesome.

2023-11-21 09:25 UTC, abhinandan13jan commented
if the lines are to be made lighter, or we are looking for some space between the arrow and the line, that can be done too

2023-11-24 08:18 UTC, MariaLeonova commented
@abhinandan13jan I'm attaching svg files here, let me know if it works, or if you need a different size / format. 
![Line Copy 5](https://github.com/openshift/hac-dev/assets/14108590/90f3f194-bd7e-43da-bdff-f6ef7d4e5170)
![Line Copy 6](https://github.com/openshift/hac-dev/assets/14108590/fadb70db-0186-4dc7-bb51-734d9d3b0340)
![Line Copy 16](https://github.com/openshift/hac-dev/assets/14108590/eb4fb18e-9527-48ef-88f0-94a358f39b43)

2023-12-01 11:03 UTC, MariaLeonova commented
LGTM

2023-12-12 09:44 UTC, sahil143 requested changes

2023-12-12 09:44 UTC, sahil143 commented on src/components/Components/ComponentDetails/tabs/ComponentNudgesDependencies.tsx
> +  const nudgedBy = component?.spec && component.spec[NudgeSpecs.NUDGED_BY];
nudged-by comes from status
```
status.build-nudged-by
```

2023-12-12 09:44 UTC, sahil143 commented on src/components/Components/ComponentDetails/tabs/ComponentNudgesDependencies.tsx
> +  const nudges = component?.spec && component.spec[NudgeSpecs.NUDGES];
spec will always be present on this resource. Also use Optional chaining instead of `&&`

```
component.spec?.[NudgeSpecs.Nudges]
```

2023-12-12 09:44 UTC, sahil143 commented on src/components/Components/ComponentDetails/tabs/ComponentNudgesDependencies.tsx
> +            id="radio-controlled"
you have same id on both Radio inputs

2023-12-12 09:44 UTC, sahil143 commented on src/components/Components/ComponentDetails/tabs/ComponentNudgesDependencies.tsx
> +                <svg
Create a separate standalone component to render the SVG based on the data passed to it.

2023-12-12 09:44 UTC, sahil143 commented on src/types/component.ts
> +  [NudgeSpecs.NUDGED_BY]?: string[];
NUDGED_BY will be in status

2023-12-27 13:30 UTC, sahil143 reviewed
/lgtm

2023-12-29 07:55 UTC, abhinandan13jan commented
/retest

2024-01-04 11:06 UTC, rohitkrai03 approved these changes
/approve

2024-01-04 11:37 UTC, merged