Optimize Import flow api requests
openshift/hac-dev pull request #881
Opened 2023-12-12 14:25 UTC by sahil143

## Fixes 

https://issues.redhat.com/browse/HAC-4812

## Description

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
**Get UX suggestion on the modal text**

![Kapture 2023-12-12 at 18 08 58](https://github.com/openshift/hac-dev/assets/9278015/f3389910-9bbd-416e-b3c0-15e249634b9e)

## How to test or reproduce?

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2023-12-14 12:22 UTC, Misjohns commented
The placement of the helper text should be closer to the progress bar. 
See PF styling here: https://www.patternfly.org/components/progress#helper-text

Also, the length of the track (light blue bar) should be fixed. It seems to change based on the percentage being displayed.

2023-12-14 15:18 UTC, rottencandy commented
We should also probably remove the 'x' button since it doesn't do anything

![0](https://github.com/openshift/hac-dev/assets/20013884/53a97f43-97c4-4da3-be6d-9e25e7cc370a)

2023-12-14 15:33 UTC, wolfeallison commented
For the progress bar title, although "Hold onto your hats!!" made me laugh, we should change it to "Importing components" to match PatternFly's guidance https://www.patternfly.org/components/progress/design-guidelines/#content-considerations

2023-12-18 07:59 UTC, sahil143 commented
@rottencandy @Misjohns Addressed review comments.
Progress bar length was changing because of change in percentage outside the progress bar.

> The placement of the helper text should be closer to the progress bar.
See PF styling here: https://www.patternfly.org/components/progress#helper-text

There is no extra styling applied to the progress bar or the helper text. This is the styling coming from the patternfly.

<img width="953" alt="image" src="https://github.com/openshift/hac-dev/assets/9278015/9513d11c-adcd-421f-9bff-24df30cffc97">

2023-12-19 17:41 UTC, rottencandy approved these changes
/lgtm

The dispatch method seems a bit convoluted, but can't think of any other way to do it.

2023-12-20 14:51 UTC, rohitkrai03 requested changes
Overall works well. Let's just remove the condition of 5 or more components to show the progress modal.

2023-12-20 14:51 UTC, rohitkrai03 commented on src/components/ImportForm/GitImportForm.tsx
> +      if (detectedComponents.length > 5) {
I think it would be better if we show the modal all the time and be consistent with the experience.

2023-12-20 14:59 UTC, rohitkrai03 requested changes

2023-12-20 14:59 UTC, rohitkrai03 commented on src/components/ImportForm/GitImportForm.tsx
> +          title="Importing components"
Also consider adding a dynamic title for the modal based on number of components being imported.

2024-01-02 09:27 UTC, rohitkrai03 approved these changes
/approve

2024-01-02 09:33 UTC, merged