feat(theme): retheme UI for Konflux
openshift/hac-dev pull request #929
Opened 2024-05-13 13:58 UTC by rohitkrai03

## Fixes 

- https://issues.redhat.com/browse/HAC-5713

## Description

- Updates to the overall theme of the UI for Konflux.

## Type of change

- [x] Feature

## Screen shots / Gifs for design review 

https://github.com/openshift/hac-dev/assets/6041994/6f05ed4e-d98b-4846-98fe-12aca64d3aaa

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2024-05-14 13:04 UTC, rohitkrai03 commented
/retest

2024-05-15 05:09 UTC, sahil143 requested changes
we should change the color for actions button also
<img width="1428" alt="image" src="https://github.com/openshift/hac-dev/assets/9278015/89693fe3-e1f2-4f53-86c1-7267add4d980">

====================================

remove this section from overview page
<img width="462" alt="image" src="https://github.com/openshift/hac-dev/assets/9278015/694d72d3-0d22-41c4-917f-21c59ead9149">

2024-05-15 11:18 UTC, rohitkrai03 commented on src/components/ApplicationDetails/ApplicationThumbnail.tsx
> +];
All the thumbnails are same. Just added one extra `asset11`. I've just replaced the SVG assets so everything should work fine with new or old applications.

2024-05-15 11:19 UTC, rohitkrai03 commented
> we should change the color for actions button also <img alt="image" width="1428" src="https://private-user-images.githubusercontent.com/9278015/330663050-89693fe3-e1f2-4f53-86c1-7267add4d980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzIxMDQsIm5iZiI6MTcxNTc3MTgwNCwicGF0aCI6Ii85Mjc4MDE1LzMzMDY2MzA1MC04OTY5M2ZlMy1lMWYyLTRmNTMtODZjMS03MjY3YWRkNGQ5ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTExNjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM5OTUzMDZlMGUyZmI5YzJiYzg5MjViMGM4ZjA1Mjc0ODFkNjQyY2RlMjM4ZTczMDE0YzFlNDM1YTgyYzE4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ip_V087DPusmu-Ny-D0_bkbiHSU7mlFNXkADQmi9WlY">
> 
> ====================================
> 
> remove this section from overview page <img alt="image" width="462" src="https://private-user-images.githubusercontent.com/9278015/330665247-694d72d3-0d22-41c4-917f-21c59ead9149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzIxMDQsIm5iZiI6MTcxNTc3MTgwNCwicGF0aCI6Ii85Mjc4MDE1LzMzMDY2NTI0Ny02OTRkNzJkMy0wZDIyLTQxYzQtOTE3Zi0yMWM1OWVhZDkxNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTExNjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YyYzE2NGEwNTJiMzUwZTEwYmQ5ZGUzNWJkMjU2YmJjZWRmODRmYWQwYTBhYzI5N2Y5MjI2Mjc4NGJhZGJlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cl9xztGN_Vj9eZWdzIPBvg8FPNZiwOecOBdSWz2cGKU">

Both of these are based on UX designs. There was no updates to the action buttons in UX designs.

2024-05-15 12:27 UTC, MariaLeonova commented
Actions buttons should be treated in the same way as the primary button, great catch, @sahil143 !

And for the removal you are suggesting only the deployment card? I would agree, since we are removing everything that mentions deployments. I wonder if we could / should replace it with something else? possibly one of these: https://konflux-ci.dev/

2024-05-15 13:52 UTC, rohitkrai03 commented
Updated the action buttons - 
![Screenshot 2024-05-15 at 7 15 36 PM](https://github.com/openshift/hac-dev/assets/6041994/b1ba1781-27a0-4eb8-b110-31c8cd768e5d)

Used integration test content from konflux website.
<img width="678" alt="Screenshot 2024-05-15 at 7 20 37 PM" src="https://github.com/openshift/hac-dev/assets/6041994/ed037334-cf46-498d-ae5e-7876a8d8c9c1">

@sahil143 @MariaLeonova

2024-05-15 15:17 UTC, abhinandan13jan commented
This isn't related to this PR, but this quickstart is creating this issue. Changes looks good elsewhere
<img width="1792" alt="Screenshot 2024-05-15 at 8 40 22 PM" src="https://github.com/openshift/hac-dev/assets/24852534/6d63e1bb-7507-4906-afc1-51ebd088ca69">

2024-05-16 04:36 UTC, sahil143 requested changes
On releases and User Access color of actions button is blue.
<img width="1432" alt="image" src="https://github.com/openshift/hac-dev/assets/9278015/2f37d513-a070-45be-a1d5-d87499e237d4">

2024-05-16 10:23 UTC, rohitkrai03 commented
> On releases and User Access color of actions button is blue. <img alt="image" width="1432" src="https://private-user-images.githubusercontent.com/9278015/331049868-2f37d513-a070-45be-a1d5-d87499e237d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Mzc5NDQsIm5iZiI6MTcxNTgzNzY0NCwicGF0aCI6Ii85Mjc4MDE1LzMzMTA0OTg2OC0yZjM3ZDUxMy1hMDcwLTQ1YmUtYTFkNS1kODc0OTllMjM3ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMDUzNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE2NDQ3OTk1Mjc3MzRhOTkxYjAzMjk3OTM5NzliZWE3M2FlZWIxZGNiY2I1MzFlMDkwNmUzZDc5OTAxZjhlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YoxGPwtQyNUPBiEy-rOIa89SaOOLeviFnPxHBvQjcsM">

Updated.

2024-05-16 14:29 UTC, abhinandan13jan commented
/lgtm

2024-05-16 14:53 UTC, merged