Replace samples catalog with simple tile selector
openshift/hac-dev pull request #95
Opened 2022-05-09 15:54 UTC by rottencandy

## Fixes 
https://issues.redhat.com/browse/HAC-1239

## Description
Replace the use of `CatalogView` with a simple tile selector.

## Type of change

- [x] Refactoring (no functional changes, no api changes)

## Screen shots / Gifs for design review 
![0](https://user-images.githubusercontent.com/20013884/167448853-721fc536-1bff-4cc5-9211-87515328754e.png)

## How to test or reproduce?
Navigate to sample selection page.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

2022-05-10 10:16 UTC, rohitkrai03 requested changes

2022-05-10 10:16 UTC, rohitkrai03 commented on src/components/ComponentSamples/ComponentSamplesPage.tsx
> +        <StatusBox data={items} loaded={loaded} loadError={loadError} label="Catalog items">
Its better to be consistent with the loading animation here. We're using PF spinner everywhere, we could use that here or the skeleton loader.

2022-05-10 10:16 UTC, rohitkrai03 commented on src/components/ComponentSamples/ComponentSamplesPage.tsx
> +          <Toolbar>
For consistent spacing around the toolbar.

```suggestion
          <Toolbar usePageInsets>
```

2022-05-11 13:17 UTC, rohitkrai03 approved these changes
/approve
/lgtm

2022-05-11 14:18 UTC, rottencandy commented
Missed a data-test attribute which was causing CI to fail, fixed.

2022-05-11 16:57 UTC, merged