Update workspace tooltip
openshift/hac-dev pull request #972
Opened 2024-08-05 12:28 UTC by abhinandan13jan

## Fixes 

https://issues.redhat.com/browse/KFLUXBUGS-1492

## Description

Updates User access tooltip in GrantAccess Page

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

<img width="647" alt="Screenshot 2024-08-05 at 5 43 58 PM" src="https://github.com/user-attachments/assets/199a3b91-cbc8-45f0-bbec-192dcf299428">

## How to test or reproduce?

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

2024-08-12 10:33 UTC, abhinandan13jan commented
/retest

2024-08-13 11:49 UTC, sahil143 requested changes

2024-08-13 11:49 UTC, sahil143 commented on src/components/UserAccess/UserAccessForm/UsernameSection.tsx
> +            aria-label="Usernames in KONFLUX"
change at other places also
```suggestion
            aria-label="Usernames in Konflux"
```

2024-08-13 13:23 UTC, Katka92 commented
/retest

2024-08-19 16:45 UTC, abhinandan13jan commented
/retest

2024-08-21 10:51 UTC, rohitkrai03 approved these changes
/approve

2024-08-21 11:52 UTC, merged